{
 "title": "Application Overview",
 "description": "Per-application metrics and logs",
 "tags": [
  "cadvisor",
  "docker",
  "lido",
  "apps",
  "hot"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(up{env=~\".+\",job=~\"cadvisor.*\"},env)"
    }
   },
   {
    "name": "source",
    "label": "Host",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{env=~\"$env\",job=~\"cadvisor.*\"},source)"
    }
   },
   {
    "name": "host",
    "label": "Source",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{env=~\"$env\",job=~\"cadvisor.*\",source=~\"$source\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{env=~\"$env\",instance=~\"$host\",job=~\"cadvisor.*\",source=~\"$source\",instance=~\"$host\"},name)"
    }
   },
   {
    "name": "web_log_target",
    "label": "Web Log",
    "query": {
     "query": "label_values(netdata_web_log_status_code_responses_total{instance=~\"$host\",source=~\"${source}\"},chart)"
    }
   },
   {
    "name": "http_status_code",
    "label": "HTTP Status",
    "query": {
     "query": "label_values(netdata_web_log_status_code_responses_total{instance=~\"$host\",source=~\"${source}\",chart=~\"web_log_($web_log_target)\\\\..+\"},dimension)"
    }
   },
   {
    "name": "http_method",
    "label": "HTTP Method",
    "query": {
     "query": "label_values(netdata_web_log_http_method_requests_total{instance=~\"$host\",source=~\"${source}\",chart=~\"web_log_($web_log_target)\\\\..+\"},dimension)"
    }
   },
   { "name": "search", "label": "Search Logs" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Timings (total, ${host})",
   "type": "heatmap",
   "description": "Response time distributed by range from 0 to XX. Each bucket contains count of requests with response time below the margin (see bucket's name).\n\nFor example:\n\n- 50 ms - count of responses with 0 < X < 50ms\n- 100 ms - count of responses with  < X < 100ms\n- 200 ms - count of responses with  < X < 200ms\n- ...\n- +Inf - count of responses with  < X < Infinity\n\nWhere last bucket includes all requests.\n\nFor additional information on histograms see [this article](https://prometheus.io/docs/practices/histograms/).\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(netdata_web_log_requests_processing_time_histogram_total{env=~\"$env\",instance=~\"${host}:.+\",source=~\"${source}\",chart=~\"web_log_($web_log_target)\\\\..+\"}[10m])) by (dimension)",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Visitors by country ($web_log_target)",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (country) (count_over_time({job=\"nginx\",env=~\"$env\",instance=~\"$host\",source=~\"$source\",vhost=~\"$web_log_target\",status=~\"${http_status_code}\",method=~\"${http_method}\"} | json | country != \"\" | __error__ = \"\" [$__interval]))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Requests by Virtual host",
   "type": "timeseries",
   "description": "HTTP requests by virtual host",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(netdata_web_log_vhost_requests_total{env=~\"$env\",instance=~\"$host:.+\",source=~\"${source}\",chart=~\"web_log_($web_log_target)\\\\..+\"}[10m])) by (dimension) > 0",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Access logs ($web_log_target)",
   "type": "logs",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "{job=\"nginx\",env=~\"$env\",instance=~\"$host\",source=~\"$source\",vhost=~\"$web_log_target\",status=~\"${http_status_code}\",method=~\"${http_method}\"} |~ \"$search\" | json | line_format \"➡️ {{.status}} for {{.request_method}} {{.request_uri}} from {{.cf_connecting_ip}}/{{.country}}\""
    }
   ]
  },
  {
   "title": "HTTP Statuses",
   "type": "timeseries",
   "description": "HTTP response codes:\n\n- 1xx Informational\n- 2xx Success\n- 3xx Redirection\n- 4xx Client Error\n- 5xx Server Error\n\nFor additional info see [this article](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(netdata_web_log_status_code_responses_total{env=~\"${env}\",instance=~\"${host}:.+\",source=~\"${source}\",chart=~\"web_log_($web_log_target)\\\\..+\",dimension=~\"${http_status_code}\"}[10m])) by (dimension) > 0",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "HTTP methods",
   "type": "timeseries",
   "description": "Count of requests per HTTP method:\n\n- GET\n- POST\n- HEAD\n- PUT\n- DELETE\n\nAnd others. For additional information see [this article](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods).",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(netdata_web_log_http_method_requests_total{env=~\"$env\",instance=~\"${host}:.+\",source=~\"${source}\",chart=~\"web_log_($web_log_target)\\\\..+\",dimension=~\"${http_method}\"}[10m])) by (dimension) > 0",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage ($container)",
     "type": "timeseries",
     "description": "Cumulative cpu time consumed",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(irate(container_cpu_user_seconds_total{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}[5m])) by (name) *100) + (sum(irate(container_cpu_system_seconds_total{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}[5m])) by (name) *100)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Container logs ($container)",
     "type": "logs",
     "gridPos": { "h": 20, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "{env=~\"$env\",source=~\"$source\",container_name=~\"$container\"} |~ \"$search\""
      }
     ]
    },
    {
     "title": "Disk bandwidth $container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_fs_reads_bytes_total{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}[5m])) by (name)) + (sum(irate(container_fs_writes_bytes_total{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}[5m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Usage ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Network Traffic ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_bytes_total{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}[5m])) by (name)) + (sum(irate(container_network_transmit_bytes_total{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}[5m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU User ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_user_seconds_total{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}[5m])) by (name) *100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "CPU System ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_system_seconds_total{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}[5m])) by (name) *100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Usage ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Cached ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_cache{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk read bandwidth ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_fs_reads_bytes_total{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk write bandwidth ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_fs_writes_bytes_total{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Received Network Traffic ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sent Network Traffic ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Processes ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_processes{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Threads ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_threads{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Opened FDs ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_file_descriptors{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sockets ($container)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_sockets{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Info",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "(time() - container_start_time_seconds{instance=~\"$host:.+\",source=~\"$source\", name=~\"$container\",name=~\".+\"})/86400",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "HTTP statuses ($web_log_target, $http_status_code)",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(25, sum(count_over_time({job=\"nginx\",status=~\"${http_status_code}\",vhost=~\"${web_log_target}\"} | json | __error__=\"\" | line_format \"{{.vhost}}\" [$__range])) by (vhost, request_uri))"
      }
     ]
    },
    {
     "title": "Container uptime ($container)",
     "type": "status-history",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() - max(container_start_time_seconds{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\",container_label_com_docker_compose_service=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Containers by state",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(container_tasks_state{env=~\"$env\",instance=~\"$host:.+\",source=~\"$source\",name=~\"$container\"} > 0) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  }
 ]
}