{
 "title": "Geth node",
 "description": "Geth metrics overview dashboard.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "container", "query": "geth-node" },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   {
    "name": "log_level",
    "label": "LogLevel",
    "query": "FATAL,ERROR,WARN,INFO,DEBUG,TRACE"
   },
   { "name": "search", "label": "Search Logs" }
  ]
 },
 "panels": [
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(chain_head_header{service=\"geth\"})"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chain_head_receipt{service=\"geth\"})"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chain_head_block{service=\"geth\"})"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(txpool_pending{service=\"geth\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(txpool_queued{service=\"geth\"})"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(txpool_local{service=\"geth\"})"
    }
   ]
  },
  {
   "title": "Container logs ($container)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{container_name=\"geth-node\"} | pattern \"<level> [<time>] <msg>\" | level=~\".*($log_level).*\" |~ \"$search\""
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(chain_head_header{service=\"geth\"})",
     "legendFormat": "header"
    },
    {
     "expr": "sum(chain_head_receipt{service=\"geth\"})",
     "legendFormat": "receipt"
    },
    {
     "expr": "sum(chain_head_block{service=\"geth\"})",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(txpool_pending{service=\"geth\"})",
     "legendFormat": "executable"
    },
    {
     "expr": "sum(txpool_queued{service=\"geth\"})",
     "legendFormat": "gapped"
    },
    {
     "expr": "sum(txpool_local{service=\"geth\"})",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(chain_execution{quantile=\"$quantile\", service=\"geth\"})",
     "legendFormat": "execution (q=$quantile)"
    },
    {
     "expr": "sum(chain_validation{quantile=\"$quantile\", service=\"geth\"})",
     "legendFormat": "validation (q=$quantile)"
    },
    {
     "expr": "sum(chain_write{quantile=\"$quantile\", service=\"geth\"})",
     "legendFormat": "commit (q=$quantile)"
    },
    {
     "expr": "sum(chain_account_reads{quantile=\"$quantile\", service=\"geth\"})",
     "legendFormat": "account read (q=$quantile)"
    },
    {
     "expr": "sum(chain_account_updates{quantile=\"$quantile\", service=\"geth\"})",
     "legendFormat": "account update (q=$quantile)"
    },
    {
     "expr": "sum(chain_account_hashes{quantile=\"$quantile\", service=\"geth\"})",
     "legendFormat": "account hashe (q=$quantile)"
    },
    {
     "expr": "sum(chain_account_commits{quantile=\"$quantile\", service=\"geth\"})",
     "legendFormat": "account commit (q=$quantile)"
    },
    {
     "expr": "sum(chain_storage_reads{quantile=\"$quantile\", service=\"geth\"})",
     "legendFormat": "storage read (q=$quantile)"
    },
    {
     "expr": "sum(chain_storage_updates{quantile=\"$quantile\", service=\"geth\"})",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "sum(chain_storage_hashes{quantile=\"$quantile\", service=\"geth\"})",
     "legendFormat": "storage hashe (q=$quantile)"
    },
    {
     "expr": "sum(chain_storage_commits{quantile=\"$quantile\", service=\"geth\"})",
     "legendFormat": "storage commit (q=$quantile)"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(txpool_valid{service=\"geth\"}[1m]))",
     "legendFormat": "valid"
    },
    {
     "expr": "sum(rate(txpool_invalid{service=\"geth\"}[1m]))",
     "legendFormat": "invalid"
    },
    {
     "expr": "sum(rate(txpool_underpriced{service=\"geth\"}[1m]))",
     "legendFormat": "underpriced"
    },
    {
     "expr": "sum(rate(txpool_pending_discard{service=\"geth\"}[1m]))",
     "legendFormat": "executable discard"
    },
    {
     "expr": "sum(rate(txpool_pending_replace{service=\"geth\"}[1m]))",
     "legendFormat": "executable replace"
    },
    {
     "expr": "sum(rate(txpool_pending_ratelimit{service=\"geth\"}[1m]))",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "sum(rate(txpool_pending_nofunds{service=\"geth\"}[1m]))",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "sum(rate(txpool_queued_discard{service=\"geth\"}[1m]))",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "sum(rate(txpool_queued_replace{service=\"geth\"}[1m]))",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "sum(rate(txpool_queued_ratelimit{service=\"geth\"}[1m]))",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "sum(rate(txpool_queued_nofunds{service=\"geth\"}[1m]))",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(system_cpu_sysload{service=\"geth\"})",
     "legendFormat": "system"
    },
    {
     "expr": "sum(system_cpu_syswait{service=\"geth\"})",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(system_cpu_procload{service=\"geth\"})",
     "legendFormat": "geth"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(system_memory_allocs{service=\"geth\"}[1m]))",
     "legendFormat": "alloc"
    },
    {
     "expr": "sum(system_memory_used{service=\"geth\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(system_memory_held{service=\"geth\"})",
     "legendFormat": "held"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(system_disk_readbytes{service=\"geth\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(system_disk_writebytes{service=\"geth\"}[1m]))",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(p2p_ingress{service=\"geth\"}[1m]))",
     "legendFormat": "ingress"
    },
    {
     "expr": "sum(rate(p2p_egress{service=\"geth\"}[1m]))",
     "legendFormat": "egress"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(p2p_peers{service=\"geth\"})",
     "legendFormat": "peers"
    },
    {
     "expr": "sum(rate(p2p_dials{service=\"geth\"}[1m]))",
     "legendFormat": "dials"
    },
    {
     "expr": "sum(rate(p2p_serves{service=\"geth\"}[1m]))",
     "legendFormat": "serves"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(eth_db_chaindata_disk_read{service=\"geth\"}[1m]))",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "sum(rate(eth_db_chaindata_disk_write{service=\"geth\"}[1m]))",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "sum(rate(eth_db_chaindata_ancient_read{service=\"geth\"}[1m]))",
     "legendFormat": "ancient read"
    },
    {
     "expr": "sum(rate(eth_db_chaindata_ancient_write{service=\"geth\"}[1m]))",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(eth_db_chaindata_disk_read{service=\"geth\"})",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "sum(eth_db_chaindata_disk_write{service=\"geth\"})",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "sum(eth_db_chaindata_ancient_read{service=\"geth\"})",
     "legendFormat": "ancient read"
    },
    {
     "expr": "sum(eth_db_chaindata_ancient_write{service=\"geth\"})",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(eth_db_chaindata_disk_size{service=\"geth\"})",
     "legendFormat": "leveldb"
    },
    {
     "expr": "sum(eth_db_chaindata_ancient_size{service=\"geth\"})",
     "legendFormat": "ancient"
    }
   ]
  },
  {
   "title": "Trie Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clean cache",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(trie_memcache_clean_read{service=\"geth\"}[1m]))",
       "legendFormat": "hit"
      },
      {
       "expr": "sum(rate(trie_memcache_clean_write{service=\"geth\"}[1m]))",
       "legendFormat": "miss"
      }
     ]
    },
    {
     "title": "Dirty cache",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(trie_memcache_gc_size{service=\"geth\"}[1m]))",
       "legendFormat": "gc"
      },
      {
       "expr": "sum(rate(trie_memcache_flush_size{service=\"geth\"}[1m]))",
       "legendFormat": "overflow"
      },
      {
       "expr": "sum(rate(trie_memcache_commit_size{service=\"geth\"}[1m]))",
       "legendFormat": "commit"
      }
     ]
    }
   ]
  }
 ]
}