{
 "title": "Lighthouse",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "log_level",
    "label": "LogLevel",
    "query": "OFF,CRIT,ERRO,WARN,INFO,DEBG,TRCE"
   },
   { "name": "search", "label": "LogSearch" },
   { "name": "service", "query": "lighthouse" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime ($service)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{service=~\"$service\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "EL connected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sync_eth1_connected{service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Synced",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sync_eth2_synced{service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "EL errors total",
   "type": "stat",
   "description": "Total number of EL request errors",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(eth1_endpoint_errors{service=~\"$service\"}[$__range])"
    }
   ]
  },
  {
   "title": "5xx served",
   "type": "stat",
   "description": "Count of served HTTP requests with 5xx status codes returned",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_api_status_codes_total{service=~\"$service\",status=~\"5.+\"}[$__range])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peers Count ($service)",
   "type": "stat",
   "description": "Total number of peers connected to the selected nodes.",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_peers{service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Epochs since finalization",
   "type": "stat",
   "description": "Number of epochs since the last finalized",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "slotclock_present_epoch{service=~\"$service\"} - beacon_head_state_finalized_epoch{service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Epochs since justification",
   "type": "stat",
   "description": "Number of epochs since the last justified",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "slotclock_present_epoch{service=~\"$service\"} - beacon_head_state_current_justified_epoch{service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "The current epoch according to system time",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "slotclock_present_epoch{service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slots behind",
   "type": "stat",
   "description": "Number of slots the head block is behind",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "slotclock_present_slot{service=~\"$service\"} - beacon_head_state_slot{service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current slot",
   "type": "stat",
   "description": "Current slot according to system time",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "slotclock_present_slot{service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "API responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "95th percentile response time by path",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (path, le) (rate(http_api_paths_times_bucket[1h]))) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Average response time by path",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_api_paths_times_sum[1h])) / sum by (path) (rate(http_api_paths_times_count[1h])) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Serve errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(http_api_status_codes_total{service=~\"$service\",status!~\"200.+\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Served requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "rate(http_api_status_codes_total{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Load (loadavg 1m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_loadavg_1{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Resident Memory Usage ($service)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Available disk space",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "disk_node_bytes_free{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cores",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cpu_cores{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cpu_threads{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Virtual memory",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "system_virt_mem_total_bytes{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Free",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "system_virt_mem_free_bytes{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DB usage",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "store_disk_db_size{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs lighthouse-node",
     "type": "logs",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "{compose_project=\"lighthouse-node\"} | json | level=~\".*($log_level).*\" |~ \"$search\""
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slots since Best Block",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "slotclock_present_slot{service=~\"$service\"} - beacon_head_state_slot{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Epoch Boundaries since Finalization (Min)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "slotclock_present_epoch{service=~\"$service\"} - beacon_head_state_finalized_epoch{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Epoch Boundaries since Justification (Min)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "slotclock_present_epoch{service=~\"$service\"} - beacon_head_state_current_justified_epoch{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Fork Choice Re-Orgs",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "beacon_fork_choice_reorg_total{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BeaconChain processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Processing Total Time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(beacon_block_processing_seconds_sum{service=~\"$service\"}[$__rate_interval])\n/\nrate(beacon_block_processing_seconds_count{service=~\"$service\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Find & Update Head Routine (1m avg)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(beacon_fork_choice_seconds_sum{service=~\"$service\"}[$__rate_interval])\n/\nrate(beacon_fork_choice_seconds_count{service=~\"$service\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Syncing Slots per Second",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sync_slots_per_second{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Peers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "libp2p Connected Peers ($service)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(libp2p_peers{service=~\"$service\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Peer Sync Status",
     "type": "piechart",
     "description": "Peers sync status",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(sync_peers_per_status{service=~\"$service\"}) by (sync_status)",
       "legendFormat": "{{sync_status}}"
      }
     ]
    },
    {
     "title": "Total Libp2p Bandwidth ($service)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(libp2p_total_bandwidth{service=~\"$service\"}[$__rate_interval])",
       "legendFormat": "bytes/s"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "On-Disk Database Size (Hot DB Only)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "store_disk_db_size{service=~\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DB Throughput (Read) per Minute",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "increase(store_disk_db_read_bytes_total{service=~\"$service\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DB Throughput (Write) (1m avg)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "increase(store_disk_db_write_bytes_total{service=~\"$service\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}