{
 "title": "Logging debug",
 "tags": [
  "logs",
  "logging",
  "debug",
  "hot"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "label_values({job=~\".+\",env=~\".+\"}, env)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({env=~\"$env\",job=~\".+\"},job)"
   },
   {
    "name": "source",
    "label": "Source",
    "query": "label_values({env=~\"$env\",job=~\"$job\",source=~\".+\"},source)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values({env=~\"$env\",job=~\"$job\",source=~\"$source\"},container_name)"
   },
   { "name": "search", "label": "Search Logs" }
  ]
 },
 "panels": [
  {
   "title": "Available logs (env: $env, job: $job, src: $source, cnt: $container)",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{env=~\"${env}\",job=~\"${job}\",source=~\"${source}\",container_name=~\"${container}\"} |~ \"$search\""
    }
   ]
  },
  { "title": "Logs stats (general)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Logs rate by host (env: $env, job: $job, src: $source)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate({env=~\"${env}\",job=~\"${job}\",source=~\"${source}\"} |~ \"$search\" [1m])) by (source)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Logs rate by job (env: $env, job: $job, src: $source)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate({env=~\"${env}\",job=~\"${job}\",source=~\"${source}\"} |~ \"$search\" [1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Logs rate by contaner (env: $env, job: docker, src: $source, cnt: $container)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate({env=~\"${env}\",job=\"docker\",source=~\"${source}\"} |~ \"$search\" [1m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Logs rate by env (env: $env, job: $job, src: $source, cnt: $container)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate({env=~\"${env}\",job=~\"${job}\",source=~\"${source}\"} |~ \"$search\" [1m])) by (env)",
     "legendFormat": "{{env}}"
    }
   ]
  }
 ]
}