---
ethereum_nodes:
  hosts:
    ethereum-nodes-1:
      ansible_host: "{{ lookup('env','ETHEREUM_NODES_IP') }}"
      wireguard_address: "10.8.0.101/24"
  vars:
    lighthouse_node_metrics_port: 8008
    node_jwtsecret: "{{ lookup('env','JWT_TOKEN') }}"
    geth_node_authrpc_port: 8551
    geth_node_metrics_port: 6060

validators_ejector:
  hosts:
    validators-ejector-1:
      ansible_host: "{{ lookup('env','VALIDATORS_EJECTOR_IP') }}"
      wireguard_address: "10.8.0.102/24"
  vars:
    # Node API Keys
    lido_keys_api_http_ext_port: 3000
    lido_keys_api_chain_id: 1
    lido_keys_api_image_tag: "@sha256:76f5a48f0baab46ada3bf4b09bdb115a74803a7ba53e783e505436d8177383dc"
    lido_keys_api_db_password: "{{ lookup('env','LIDO_KEYS_API_DB_PASSWORD') }}"
    lido_keys_api_el_rpc_url_list:
      - "http://{{ (hostvars[groups.ethereum_nodes[0]]).wireguard_address.split('/')[0] }}:8545"
    lido_keys_api_cl_api_url_list:
      - "http://{{ (hostvars[groups.ethereum_nodes[0]]).wireguard_address.split('/')[0] }}:5051"
    # Validators Ejector
    lido_validator_ejector_prometheus_port: 8989
    lido_validator_ejector_image_tag: "@sha256:e3acb5eb1bab5a871bf70e9bb736e1a1016567e1846a9b96c27232c84643597a"
    lido_validator_ejector_execution_node:
      - "http://{{ (hostvars[groups.ethereum_nodes[0]]).wireguard_address.split('/')[0] }}:8545"
    lido_validator_ejector_consensus_node:
      - "http://{{ (hostvars[groups.ethereum_nodes[0]]).wireguard_address.split('/')[0] }}:5051"
    lido_validator_ejector_operator_id: "{{ lookup('env','VALIDATOR_EJECTOR_OPERATOR_ID') }}"
    lido_validator_ejector_staking_module_id: "{{ lookup('env','VALIDATOR_EJECTOR_STAKING_MODULE_ID') }}"
    lido_validator_ejector_messages_password: "{{ lookup('env','VALIDATOR_EJECTOR_MESSAGES_PASSWORD') }}"
    lido_validator_ejector_locator_address: "0xC1d0b3DE6792Bf6b4b37EccdcC24e45978Cfd2Eb"
    validator_ejector_oracle_addresses_allowlist:
      - "0x140Bd8FbDc884f48dA7cb1c09bE8A2fAdfea776E"
      - "0x1d0813bf088BE3047d827D98524fBf779Bc25F00"
      - "0x404335BcE530400a5814375E7Ec1FB55fAff3eA2"
      - "0x946D3b081ed19173dC83Cd974fC69e1e760B7d78"
      - "0x007DE4a5F7bc37E2F26c0cb2E8A95006EE9B89b5"
      - "0xEC4BfbAF681eb505B94E4a7849877DC6c600Ca3A"
      - "0x61c91ECd902EB56e314bB2D5c5C07785444Ea1c8"
      - "0x1Ca0fEC59b86F549e1F1184d97cb47794C8Af58d"
      - "0xA7410857ABbf75043d61ea54e07D57A6EB6EF186"

monitoring_server:
  hosts:
    monitoring-node-1:
      ansible_host: "{{ lookup('env','MONITORING_SERVER_IP') }}"
      wireguard_address: "10.8.0.103/24"
  vars:
    alerts_box_grafana_user: "{{ lookup('env','ALERTS_BOX_GRAFANA_USER') }}"
    alerts_box_grafana_password: "{{ lookup('env','ALERTS_BOX_GRAFANA_PASSWORD') }}"
    telegram_bot_token: "{{ lookup('env','TELEGRAM_BOT_TOKEN') }}"
    telegram_chat_id: "{{ lookup('env','TELEGRAM_CHAT_ID') }}"

all:
  vars:
    containers_basedir: "/srv"
    compose_retries: 11
    compose_retries_delay_sec: 3
    docker_log_loki_url: "http://{{ (hostvars[groups.monitoring_server[0]]).wireguard_address.split('/')[0] }}:3100/loki/api/v1/push"
    docker_loki_plugin_required: true
    docker_loki_batch_size: "102400"
    docker_loki_batch_wait: "1s"
    docker_loki_timeout: "10s"
    docker_loki_backoff_min: "100ms"
    docker_loki_backoff_max: "10s"
    docker_loki_retries: "10"
    docker_loki_buffer_size_max: "5m"
    docker_loki_mode: "non-blocking"
    docker_loki_external_labels: "{% raw %}container_name={{.Name}}{% endraw %}"
